# Generated by Django 5.0.4 on 2024-05-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0002_division_section_fighter_division_fight_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mma.division'),
        ),
    ]
