# Generated by Django 5.0.4 on 2024-05-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0003_fight_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fight',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mma.bout'),
        ),
    ]
