# Generated by Django 5.0.4 on 2024-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0005_alter_fight_review_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
