# Generated by Django 5.0.4 on 2024-06-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0006_thread_thread_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread_comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_comment_replies', to=settings.AUTH_USER_MODEL)),
                ('likers', models.ManyToManyField(related_name='liked_thread_comment_replies', to=settings.AUTH_USER_MODEL)),
                ('thread_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mma.thread_comment')),
            ],
        ),
    ]
